name: Convert TXT to JSON

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch: # Manual trigger from GitHub Actions UI

jobs:
  convert:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Python version to run the script

    - name: Run TXT to JSON conversion script
      run: |
        python convert_txt_to_json.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add epg_data.json
        git commit -m "Update epg_data.json from TXT files"
        git push
