name: Convert TXT to JSON

on:
  push:
    branches:
      - main
  # Optional: If you want to trigger manually, uncomment the line below
  # workflow_dispatch:

jobs:
  convert_txt_to_json:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set Git Config (for committing and pushing changes)
    - name: Set Git Config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    # Step 3: Install Python (If not already installed in your environment)
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Step 4: Install Dependencies (if any, e.g., requirements.txt)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Check the content of epg_data.json before running the script
    - name: Check epg_data.json before script
      run: |
        echo "Before running script:"
        cat epg_data.json || echo "No epg_data.json file found"

    # Step 6: Run the Python script to update epg_data.json from .txt files
    - name: Run Convert TXT to JSON Script
      run: |
        python convert_txt_to_json.py

    # Step 7: Check the content of epg_data.json after running the script
    - name: Check epg_data.json after script
      run: |
        echo "After running script:"
        cat epg_data.json || echo "No epg_data.json file found"

    # Step 8: Check if changes have been made to epg_data.json
    - name: Check if epg_data.json has changes
      run: |
        git diff --exit-code || echo "Changes detected in epg_data.json"

    # Step 9: Commit and Push Changes (only if changes detected)
    - name: Commit and Push Changes (if any)
      run: |
        git status
        if ! git diff --exit-code; then
          git add epg_data.json
          git commit -m "Update epg_data.json from TXT files"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        else
          echo "No changes detected, skipping commit."
