name: Convert TXT to JSON

on:
  push:
    branches:
      - main  # Trigger the workflow on a push to the main branch

jobs:
  convert:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python (use Python 3.8 or whatever version you want)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: Run your Python script to convert TXT to JSON
    - name: Run conversion script
      run: |
        python convert_txt_to_json.py

    # Step 4: Commit and push the updated epg_data.json file
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        git add epg_data.json
        git commit -m "Update epg_data.json from TXT files"
        git push
