name: Run Scraper and Update Database

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: pip install requests beautifulsoup4

    - name: Run Scraper
      run: python scraper.py

    - name: Set up Git for Push
      uses: actions/setup-git@v2
      with:
        user-name: 'GitHub Actions'
        user-email: 'github-actions@github.com'

    - name: Commit Database
      run: |
        git add docs/epg_data.db
        git commit -m "Update database"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
